### ISSUE TITLE
Can this library programmatically catch exceptions?

### ISSUE THREAD

**Issue by ZiraiMode** [zensum/ktor-sentry-feature#5]
This 

```
        try {
            runSomething()
        } catch (e: Exception) {
            Sentry.capture(e)
        }
```

Also, does this library require some kind of Sentry import or it already contain import in itself?

**Comment by pn** [comment]
Yes, see [here](https://github.com/zensum/ktor-sentry-feature/blob/master/src/main/kotlin/se/zensum/ktorSentryFeature/sentryFeature.kt#L13).

It already pulls sentry dependency through gradle ([see here](https://github.com/zensum/ktor-sentry-feature/blob/master/build.gradle#L40)).
